const DTE_TRANSLATIONS={
  en:{
    document_title:'Dongle Screen Theme Preview',canvas_label:'Dongle screen theme preview',brand:'DONGLE SCREEN ENGINE / THEME PREVIEW',title:'Minimal theme',language:'Language',default:'Default',swipe_left:'Swipe left',tap:'Tap',swipe_up:'Swipe up',preview_hint:'This local preview drives the same C state, gesture and RGB565 render path used by firmware. It does not connect to a keyboard.',loading:'Loading theme…',controls:'PREVIEW CONTROLS',resolution:'Logical resolution',landscape:'280 × 240 · landscape',portrait:'240 × 280 · portrait',square:'240 × 240 · square',
    hardware_sim:'Hardware simulation',hardware_profile:'Hardware profile',unlimited:'Unlimited',nrf52840:'nRF52840 + ST7789',custom:'Custom',target_fps:'Target FPS',spi_clock:'SPI MHz',cpu_scale:'CPU slowdown',transport:'Transport',transport_full:'Full frame',transport_bands:'Dirty row bands',transport_packed:'Packed tile rectangles',hardware_metrics:'Hardware estimate',logical_fps:'Logical FPS',presented_fps:'Presented FPS',render_cost:'Render',transfer_cost:'Transfer',dirty_tiles:'Dirty tiles',transfer_bytes:'Transfer bytes',dropped_frames:'Dropped',model_hint:'Estimate only; calibrate CPU slowdown against measured hardware.',
    battery_layout:'Battery layout',two_batteries:'Two · split 0 / split 1',three_batteries:'Three · dongle / split 0 / split 1',dongle_battery:'Dongle battery',split0_battery:'Split 0 battery',split1_battery:'Split 1 battery',layer:'Layer',endpoint:'Endpoint',disconnected:'Disconnected',modifiers:'Modifiers',disconnect_right:'Disconnect right',unknown_battery:'Unknown battery',pause:'Pause',continue:'Continue',step:'Single frame +16.67ms',replay:'Replay',timing_hint:'60Hz is the animation timeline, not a claim that a given display transport presents every frame.',footer:'One state machine and RGB565 renderer across native, WASM and firmware.',example:'Engine example',auto:'Automatic demo · simulated data',interactive:'Interactive preview',shared_gesture:'shared C gesture recognizer',load_error:'Preview failed: ',reload:'Rebuild the preview',actions:['','style changed','information opened','default view','next page','previous page','reset']
  },
  'zh-CN':{
    document_title:'Dongle Screen 主题预览',canvas_label:'Dongle 屏幕主题预览',brand:'DONGLE SCREEN ENGINE / 主题预览',title:'极简主题',language:'语言',default:'默认视图',swipe_left:'左滑',tap:'点击',swipe_up:'上滑',preview_hint:'本地预览与固件共用 C 状态、手势及 RGB565 渲染路径，不连接实体键盘。',loading:'正在加载主题…',controls:'预览控制',resolution:'逻辑分辨率',landscape:'280 × 240 · 横屏',portrait:'240 × 280 · 竖屏',square:'240 × 240 · 方屏',
    hardware_sim:'硬件模拟',hardware_profile:'硬件档位',unlimited:'无限制',nrf52840:'nRF52840 + ST7789',custom:'自定义',target_fps:'目标 FPS',spi_clock:'SPI MHz',cpu_scale:'CPU 减速倍率',transport:'传输模式',transport_full:'整帧',transport_bands:'脏行带',transport_packed:'打包 Tile 矩形',hardware_metrics:'硬件估算',logical_fps:'逻辑 FPS',presented_fps:'呈现 FPS',render_cost:'渲染',transfer_cost:'传输',dirty_tiles:'脏 Tile',transfer_bytes:'传输字节',dropped_frames:'丢帧',model_hint:'此为估算模型；请以实机数据校准 CPU 减速倍率。',
    battery_layout:'电池布局',two_batteries:'两块 · 分体 0 / 分体 1',three_batteries:'三块 · Dongle / 分体 0 / 分体 1',dongle_battery:'Dongle 电池',split0_battery:'分体 0 电池',split1_battery:'分体 1 电池',layer:'当前层',endpoint:'输出',disconnected:'未连接',modifiers:'修饰键',disconnect_right:'断开右手',unknown_battery:'电量未知',pause:'暂停',continue:'继续',step:'单帧 +16.67ms',replay:'重播',timing_hint:'60Hz 为动画时基，并不表示任一显示链路皆能逐帧呈现。',footer:'Native、WASM 与固件共用同一状态机及 RGB565 渲染器。',example:'引擎示例',auto:'自动演示 · 模拟数据',interactive:'交互预览',shared_gesture:'共用 C 手势识别器',load_error:'预览启动失败：',reload:'请重新构建预览',actions:['','形态已切换','信息已展开','已回默认视图','下一页','上一页','已复位']
  },
  ja:{
    document_title:'Dongle Screen テーマプレビュー',canvas_label:'Dongle 画面テーマプレビュー',brand:'DONGLE SCREEN ENGINE / テーマプレビュー',title:'ミニマルテーマ',language:'言語',default:'標準表示',swipe_left:'左スワイプ',tap:'タップ',swipe_up:'上スワイプ',preview_hint:'ローカルプレビューはファームウェアと同じ C の状態、ジェスチャー、RGB565 描画経路を使用します。キーボードには接続しません。',loading:'テーマを読み込み中…',controls:'プレビュー設定',resolution:'論理解像度',landscape:'280 × 240 · 横',portrait:'240 × 280 · 縦',square:'240 × 240 · 正方形',
    hardware_sim:'ハードウェア模擬',hardware_profile:'ハードウェア構成',unlimited:'無制限',nrf52840:'nRF52840 + ST7789',custom:'カスタム',target_fps:'目標 FPS',spi_clock:'SPI MHz',cpu_scale:'CPU 低速倍率',transport:'転送方式',transport_full:'全画面',transport_bands:'更新行バンド',transport_packed:'タイル矩形パック',hardware_metrics:'ハードウェア推定',logical_fps:'論理 FPS',presented_fps:'表示 FPS',render_cost:'描画',transfer_cost:'転送',dirty_tiles:'更新タイル',transfer_bytes:'転送バイト',dropped_frames:'ドロップ',model_hint:'推定モデルです。実機値に合わせて CPU 倍率を調整してください。',
    battery_layout:'バッテリー構成',two_batteries:'2 個 · split 0 / split 1',three_batteries:'3 個 · dongle / split 0 / split 1',dongle_battery:'Dongle バッテリー',split0_battery:'Split 0 バッテリー',split1_battery:'Split 1 バッテリー',layer:'レイヤー',endpoint:'出力先',disconnected:'未接続',modifiers:'修飾キー',disconnect_right:'右側を切断',unknown_battery:'残量不明',pause:'一時停止',continue:'続行',step:'1 フレーム +16.67ms',replay:'リプレイ',timing_hint:'60Hz はアニメーション時間軸であり、表示転送が全フレームを提示する保証ではありません。',footer:'Native、WASM、ファームウェアで同一の状態機械と RGB565 レンダラーを使用します。',example:'エンジン例',auto:'自動デモ · 模擬データ',interactive:'操作プレビュー',shared_gesture:'共通 C ジェスチャー認識',load_error:'プレビューを開始できません：',reload:'プレビューを再ビルドしてください',actions:['','表示を変更','情報を表示','標準表示','次のページ','前のページ','リセット']
  }
};
(()=>{let locale='en';const t=k=>(DTE_TRANSLATIONS[locale]||DTE_TRANSLATIONS.en)[k]??DTE_TRANSLATIONS.en[k]??k;
  function set(next){locale=DTE_TRANSLATIONS[next]?next:'en';document.documentElement.lang=locale;document.title=t('document_title');document.querySelectorAll('[data-i18n]').forEach(e=>e.textContent=t(e.dataset.i18n));document.querySelectorAll('[data-i18n-aria]').forEach(e=>e.setAttribute('aria-label',t(e.dataset.i18nAria)));const picker=document.getElementById('locale');if(picker)picker.value=locale;document.dispatchEvent(new CustomEvent('dte-locale-change'));}
  const requested=new URLSearchParams(location.search).get('lang');const preferred=requested||(navigator.language.startsWith('zh')?'zh-CN':navigator.language.startsWith('ja')?'ja':'en');window.DTE_TRANSLATIONS=DTE_TRANSLATIONS;window.dteI18n={t,set,get locale(){return locale;}};set(preferred);document.getElementById('locale').onchange=e=>set(e.target.value);
})();
